# fly.toml app configuration file generated for lyrical-backend on 2023-09-12T16:19:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lyrical-backend"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = 8080